version: '3'

services:

  database:
    container_name: database
    build: 
      context: database
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8080:8080
